// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "sign-in-cognito-app-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1bb17ivbsa48o.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:d0c9cbe8-9079-43b0-88e2-14c99ee73762",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qPfQPOJs5",
    "aws_user_pools_web_client_id": "6i8ldkvphmd0b3vtr911l0efdn",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apidynamo",
            "endpoint": "https://ktk0wyq4ja.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
